wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.24
    framework: fastai
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    t:
      1:
      - 1
      - 4
      - 5
      4: 3.8.10
      5: 0.10.24
      8:
      - 1
      - 3
      - 5
