# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"JSONizerWithBool": "01_extract.ipynb",
         "getcatdict": "01_extract.ipynb"}

modules = ["utils.py",
           "core.py"]

doc_url = "https://manikyabard.github.io/transfertab/"

git_url = "https://github.com/manikyabard/transfertab/tree/master/"

def custom_doc_links(name): return None
