# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"extract_meta_from_learner": "00_ExractUtils.ipynb",
         "extract_meta_from_df": "00_ExractUtils.ipynb",
         "CustomJSONizer": "00_ExractUtils.ipynb",
         "extractembeds": "00_ExractUtils.ipynb",
         "TabTransfer": "01_transfer.ipynb"}

modules = ["utils.py",
           "core.py"]

doc_url = "https://manikyabard.github.io/transfertab/"

git_url = "https://github.com/manikyabard/transfertab/tree/master/"

def custom_doc_links(name): return None
